## Problem Solving and Programming

## SarmishtaHari

#### Day No:-13
#### Date:- 16-5-2019

## Day Objectives:
* Converting and Writing The Day13 Programs into Python
* Complete the given Problems:
* Functional Programming
* File Handling / Data Processing
* External Libraries

## File Handling

#### Problem 1:
#### Problem Statement:
Reading and Writing The Data Files

In [13]:
def readFileData(filename):
    f=open(filename,'r')
    filedata=f.read()
    
    f.close()
    return filedata
readFileData('DataFiles/Data.txt')

'Data in Line 1 \n\nData in Line 2\n\nData in Line 3'

In [8]:
def readFileData(filename):
    f=open(filename,'r')
    filedata=f.readline()
    
    f.close()
    return filedata
readFileData('DataFiles/Data.txt')

'Data in Line 1 \n'

In [14]:
def readFileData(filename):
    with open(filename,'r')as f :
        print(f.read())
        return
readFileData('DataFiles/Data.txt')

Data in Line 1 

Data in Line 2

Data in Line 3


In [10]:
def readFileData(filename):
    with open(filename,'a') as f:
        print(f.read())
        return
    
def writeIntoFile(filename,data):
    with open(filename,'w') as f:
        f.write(data)
        return
writeIntoFile('DataFiles/fileWrite.txt','random sentence into the filewrite')   

In [12]:
def readFileData(filename):
    with open(filename,'a') as f:
        print(f.read())
        return
    
def writeFileData(filename):
    with open(filename,'w') as f:
        f.write(data)
        return
writeIntoFile('DataFiles/fileWrite1.txt','First Line \n')        

#### Problem 2:
#### Problem Statement :
Define a function to generate a Marks data file(text) for 1300 students such that each mark is entered in a new line .Marks range from 0 to 100(inclusive) as random numbers.

In [8]:
import random
def generateMarksData(n,filename):
    with open(filename,'w') as marksfile:
        for i in range(0,n):
            marks= random.randint(0,101)
            marksfile.write(str(marks)+'\n')
    return       
generateMarksData(1300,'DataFiles/marksdata.txt')

#### Problem 3:
#### Problem Statement :
Generate a report on the marks data with the following indicators
* Highest Marks:
* Lowest  Marks:
* Average Marks:
* no.of students with distinction(>80):
* no.of students with first class(>60):
* no.of students with second class(>50): 
* no.of students with third class(>40):
* no.of students with failed(<40):

In [53]:
import random
def readMarksFromFile(filename):
    marks_li=[]
    with open(filename,'r') as f:
        for x in f:
            marks_li.append(int(x))
    writeMarksIntoFile('DataFiles/reportFile.txt',marks_li)
    
def writeMarksIntoFile(filename,arr):
    dist=0
    first=0
    second=0
    third=0
    fail=0
    with open(filename,'w') as reportFile:
        reportFile.write("Highest is:"+str(max(arr))+'\n')
        reportFile.write("lowest is:"+str(min(arr))+'\n')
        for i in range(0,len(arr)):
            if(arr[i]>=80):
                dist=dist+1
            elif(arr[i]>=60 and arr[i]<=80):  
                first=first+1
            elif(arr[i]>=50 and arr[i]<=60):  
                second=second+1    
            elif(arr[i]>=40 and arr[i]<=50):  
                third=third+1 
            else: 
                fail=fail+1
        reportFile.write("Distinction:"+str(dist)+'\n')  
        reportFile.write("First:"  +str(first)+'\n') 
        reportFile.write("second:" +str(second)+'\n') 
        reportFile.write("third:"  +str(third)+'\n') 
        reportFile.write("fail:"   +str(fail)+'\n') 
        return
readMarksFromFile('DataFiles/marksdata.txt')       

##  Functional Programming

In [51]:
li =[1,2,3,4,5,6]
#s = str(li)
s = list(map(str,li))
s[0]

'1'

In [52]:
li =[1,2,3,4,5,6]
#s = str(li)
s = list(map(str,li))
s

['1', '2', '3', '4', '5', '6']

In [35]:
def square(n):
    return n * n
li=[1,2,3,40,5,6]
s=list(map(square,li))
s

[1, 4, 9, 1600, 25, 36]

In [37]:
def square(n):
    return n * n
li=[1,2,3,40,5,6]
#s=str(li)
s=list(map(str,li))
s=[float(i) for i in s]
s

[1.0, 2.0, 3.0, 40.0, 5.0, 6.0]

In [56]:
import timeit #timeit is used to generate the total time taken to execute the program
def square(n):
    return n * n
st=timeit.default_timer()
li=[1,2,3,40,5,6]
#s=str(li)
s=list(map(str,li))
s=[float(i) for i in s]
print(timeit.default_timer()-st)
s

0.0001724640005704714


[1.0, 2.0, 3.0, 40.0, 5.0, 6.0]

## External Libraries

In [57]:
import numpy as np #importing libraries
a = np.array([0,1,2])

print(a)
type(a)

[0 1 2]


numpy.ndarray

In [1]:
import numpy as np #importing libraries
a = np.array([[0,1,2],[3,4,5]]) 

print(a)
type(a)

[[0 1 2]
 [3 4 5]]


numpy.ndarray

In [2]:
import numpy as np #importing libraries
a= np.array([0,1,2])
b=np.array([3,4,5])

print("matrix A\n",a)
print("matrix B\n",b)

matrix A
 [0 1 2]
matrix B
 [3 4 5]
